apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps-factory
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - service: auth
            namespace: dev-auth
          - service: payment
            namespace: dev-payment
          - service: frontend
            namespace: dev-frontend
  template:
    metadata:
      name: '{{service}}-app'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: 'https://github.com/devopsghazali/my-gitops-monorepo.git'
        targetRevision: HEAD
        path: 'apps/{{service}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
